version: '2'

networks:
  chainpoint:
    driver: bridge

services:

  # NGINX Proxy
  #
  # An auto-scaling reverse proxy that reconfigures
  # itself based on which API services are available
  # for requests.
  #
  # See : https://github.com/jwilder/nginx-proxy
  #
  # SCALED : false
  #
  # PORTS:
  # http : 80
  #
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      NODE_ENV: development
      DEFAULT_HOST: api.local
    depends_on:
      - api
    networks:
      - chainpoint

  # HTTP API
  # Restify Node public web API service.
  #
  # Note : You don't access this directly, but through
  # the nginx-proxy load balancer. This service cannot be
  # given an explicit container_name since it needs
  # to be scalable with 'docker-compose scale api=5'
  #
  # The VIRTUAL_HOST env var is used by the nginx-proxy
  # to rebuild its reverse proxy host config and must be
  # passed in by the HTTP client:
  #
  # curl -i -H 'Host: api.local' http://127.0.0.1/
  #
  # PORTS : 8080
  #
  api:
    restart: always
    image: quay.io/chainpoint/node-api-service:${DOCKER_TAG}
    build:
      context: ./node-api-service
    depends_on:
      - roach1
      - roach2
      - roach3
      - redis
      - rabbitmq
      - influxdb
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      CHAINPOINT_STACK_ID: ${CHAINPOINT_STACK_ID}
      CHAINPOINT_BASE_URI: ${CHAINPOINT_BASE_URI}
      ANCHOR_BTC: ${ANCHOR_BTC}
      ANCHOR_ETH: ${ANCHOR_ETH}
      VIRTUAL_HOST: api.local

  # Splitter
  #
  # SCALED: true
  # 
  # PORTS : none
  #
  splitter:
    restart: always
    image: quay.io/chainpoint/node-splitter-service:${DOCKER_TAG}
    build:
      context: ./node-splitter-service
    depends_on:
      - rabbitmq
      - influxdb
    networks:
      - chainpoint
    environment:
      NODE_ENV: development

  # Aggregator
  #
  # SCALED: true
  #
  # PORTS : none
  #
  aggregator:
    restart: always
    image: quay.io/chainpoint/node-aggregator-service:${DOCKER_TAG}
    build:
      context: ./node-aggregator-service
    depends_on:
      - rabbitmq
      - influxdb
      - nist-beacon
    networks:
      - chainpoint
    environment:
      NODE_ENV: development

  # NIST Beacon
  # Retrieve and store current NIST Beacon records
  # 
  # SCALED: false
  #
  # PORTS : none
  #
  nist-beacon:
    restart: always
    image: quay.io/chainpoint/node-nist-beacon-service:${DOCKER_TAG}
    build:
      context: ./node-nist-beacon-service
    container_name: nist-beacon
    depends_on:
      - redis
      - influxdb
    networks:
      - chainpoint
    environment:
      NODE_ENV: development

  # Calendar
  # Aggregate Merkle roots from the `aggregator` service instances
  # and write them to the Calendar event/block chains.
  #
  # SCALED: false
  #
  # PORTS : none
  #
  calendar:
    restart: always
    image: quay.io/chainpoint/node-calendar-service:${DOCKER_TAG}
    build:
      context: ./node-calendar-service
    container_name: calendar
    depends_on:
      - roach1
      - roach2
      - roach3
      - rabbitmq
      - influxdb
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      CHAINPOINT_STACK_ID: ${CHAINPOINT_STACK_ID}
      CHAINPOINT_BASE_URI: ${CHAINPOINT_BASE_URI}
      ANCHOR_BTC: ${ANCHOR_BTC}
      ANCHOR_ETH: ${ANCHOR_ETH}
      SIGNING_SECRET_KEY: ${SIGNING_SECRET_KEY}

  # Bitcoin Fees
  # Retrieve and store recommended transaction fees for Bitcoin
  # 
  # SCALED: false
  #
  # PORTS : none
  #
  btc-fee:
    restart: always
    image: quay.io/chainpoint/node-btc-fee-service:${DOCKER_TAG}
    build:
      context: ./node-btc-fee-service
    container_name: btc-fee
    depends_on:
      - consul
      - rabbitmq
      - influxdb
    networks:
      - chainpoint
    environment:
      NODE_ENV: development

  # Bitcoin Transmit
  # Send Calendar Block Merkle roots to be embedded in a BTC transaction.
  # 
  btc-tx:
    restart: always
    image: quay.io/chainpoint/node-btc-tx-service:${DOCKER_TAG}
    build:
      context: ./node-btc-tx-service
    container_name: btc-tx
    depends_on:
      - roach1
      - roach2
      - roach3
      - consul
      - rabbitmq
      - btc-fee
      - influxdb
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      CHAINPOINT_STACK_ID: ${CHAINPOINT_STACK_ID}
      BCOIN_API_BASE_URI: ${BCOIN_API_BASE_URI}
      BCOIN_API_WALLET_ID: ${BCOIN_API_WALLET_ID}
      BCOIN_API_USERNAME: ${BCOIN_API_USERNAME}
      BCOIN_API_PASS: ${BCOIN_API_PASS}

  # Bitcoin Transmit Monitor
  # Monitor and report on the state of BTC transactions this app has submitted.
  #
  btc-mon:
    restart: always
    image: quay.io/chainpoint/node-btc-mon-service:${DOCKER_TAG}
    build:
      context: ./node-btc-mon-service
    container_name: btc-mon
    depends_on:
      - rabbitmq
      - influxdb
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      BCOIN_API_BASE_URI: ${BCOIN_API_BASE_URI}
      BCOIN_API_WALLET_ID: ${BCOIN_API_WALLET_ID}
      BCOIN_API_USERNAME: ${BCOIN_API_USERNAME}
      BCOIN_API_PASS: ${BCOIN_API_PASS}

  # Proof State
  # Encapsulates all persistent data storage for partial proof data.
  # 
  proof-state:
    restart: always
    image: quay.io/chainpoint/node-proof-state-service:${DOCKER_TAG}
    build:
      context: ./node-proof-state-service
    depends_on:
      - rabbitmq
      - postgres
      - influxdb
    networks:
      - chainpoint
    environment:
      NODE_ENV: development
      ANCHOR_BTC: ${ANCHOR_BTC}
      ANCHOR_ETH: ${ANCHOR_ETH}

  # Proof Generation
  # Responsible for constructing, signing, and validating Chainpoint proofs
  # for Calendar, Bitcoin, and Ethereum attestation levels.
  # 
  proof-gen:
    restart: always
    image: quay.io/chainpoint/node-proof-gen-service:${DOCKER_TAG}
    build:
      context: ./node-proof-gen-service
    depends_on:
      - rabbitmq
      - influxdb
    networks:
      - chainpoint
    environment:
      NODE_ENV: development

  # InfluxDB Telegraf service
  #
  telegraf:
    restart: always
    image: telegraf:1.3.2-alpine
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      # - "8125:8125/udp"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - chainpoint

  # InfluxDB Chronograf service (Visualization)
  #
  # Admin Page
  # http://127.0.0.1:8888/
  #  
  chronograf:
    restart: always
    image: chronograf:1.3.2.1-alpine
    container_name: chronograf
    ports:
      - "8888:8888"
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    environment:
        INFLUXDB_URL: http://influxdb:8086
        KAPACITOR_URL: http://kapacitor:9092
    depends_on:
      - influxdb
    networks:
      - chainpoint

  # InfluxDB Kapacitor service (Alerting)
  #
  kapacitor:
    restart: always
    image: kapacitor:1.3.1-alpine
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    volumes:
      - ./data/kapacitor:/var/lib/kapacitor
    ports:
      - "9092:9092"
    depends_on:
      - influxdb
    networks:
      - chainpoint

  # InfluxDB Kapacitor CLI
  #   docker-compose run kapacitor-cli
  #
  kapacitor-cli:
    image: kapacitor:1.3.1-alpine
    entrypoint: ash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    depends_on:
      - influxdb
      - kapacitor
    networks:
      - chainpoint

  # InfluxDB
  #
  influxdb:
    restart: always
    image: influxdb:1.2.4-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - chainpoint

  # InfluxDB CLI
  #   docker-compose run influxdb-cli
  #
  influxdb-cli:
    image: influxdb:1.2.4-alpine
    entrypoint:
      - influx
      - -host
      - influxdb
    depends_on:
      - influxdb
    networks:
      - chainpoint

  # Postgres
  #
  # See : https://hub.docker.com/_/postgres/
  # Note: Connect locally on OS X:
  #
  # Installs local client 'psql'
  #   brew install postgres
  #
  # Connect (uname/pass chainpoint/chainpoint):
  #   psql -h 127.0.0.1 -U chainpoint
  #
  postgres:
    restart: always
    image: postgres:9.6.2-alpine
    container_name: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chainpoint
      POSTGRES_PASSWORD: chainpoint
    ports:
      - "5432:5432"
    networks:
      - chainpoint

  # RabbitMQ
  #
  # Admin Page (username:pass)
  # http://127.0.0.1:15673/ (rabbitmq:rabbitmq)
  #
  # LOCAL PORTS:
  # amqp : 5673 (+1 over default)
  # http : 15673 (+1 over default)
  #
  rabbitmq:
    restart: always
    image: rabbitmq:3.6.9-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
    - 5673:5672
    - 15673:15672
    environment:
      RABBITMQ_DEFAULT_USER: chainpoint
      RABBITMQ_DEFAULT_PASS: chainpoint
    networks:
      - chainpoint

  # Redis
  #
  # LOCAL PORTS:
  # redis : 6380 (+1 over default)
  #
  redis:
    restart: always
    image: redis:3.2.9-alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./data/redis:/data
    networks:
      - chainpoint
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  # Consul
  #
  # Consul Admin UI: http://127.0.0.1:8500
  #
  consul:
    restart: always
    image: consul:0.8.5
    container_name: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    volumes:
      - ./data/consul:/consul/data
    networks:
      - chainpoint

  # CockroachDB
  #
  # CockroachDB Admin UI: http://127.0.0.1:8080
  #
  roach1:
    restart: always
    image: cockroachdb/cockroach:v1.0.2
    container_name: roach1
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./data/roach1:/cockroach/cockroach-data
    command:
      - start
      - --insecure
    networks:
      - chainpoint

  roach2:
    restart: always
    image: cockroachdb/cockroach:v1.0.2
    container_name: roach2
    depends_on:
      - roach1
    ports:
      - 26257
    volumes:
      - ./data/roach2:/cockroach/cockroach-data
    command:
      - start
      - --insecure
      - --join
      - roach1
    networks:
      - chainpoint

  roach3:
    restart: always
    image: cockroachdb/cockroach:v1.0.2
    container_name: roach3
    depends_on:
      - roach1
      - roach2
    ports:
      - 26257
    volumes:
      - ./data/roach3:/cockroach/cockroach-data
    command:
      - start
      - --insecure
      - --join
      - roach1
    networks:
      - chainpoint

  # bcoin:
  #   image: quay.io/chainpoint/bcoin:${DOCKER_TAG}
  #   build:
  #     context: ./bcoin
  #   container_name: bcoin
  #   restart: unless-stopped
  #   ports:
  #     #-- Mainnet
  #     # - "8333:8333"
  #     # - "8332:8332" # RPC
  #     #-- Testnet
  #     - "18333:18333"
  #     - "18332:18332" # RPC
  #   environment:
  #     BCOIN_CONFIG: /root/.bcoin/bcoin.conf
  #     # VIRTUAL_HOST: bcoin.chainpoint.org
  #     # VIRTUAL_PORT: 8332 # Mainnet
  #     VIRTUAL_PORT: 18332 # Testnest
  #   volumes:
  #     - ./data/bcoin:/root/.bcoin
  #   networks:
  #     - chainpoint
