version: '3'

services:
  calendar:
    restart: always
    image: chainpoint/node-calendar-service
    container_name: calendar
    build:
      context: ./node-calendar-service
    depends_on:
      - l5d
      - rabbitmq

  aggregator:
    restart: always
    image: chainpoint/node-aggregator-service
    container_name: aggregator
    build:
      context: ./node-aggregator-service
    depends_on:
      - l5d
      - rabbitmq

  proof:
    restart: always
    image: chainpoint/node-proof-service
    container_name: proof
    build:
      context: ./node-proof-service
    depends_on:
      - l5d
      - rabbitmq

  # HTTP API front-end chainpoint/node-web-service
  web:
    restart: always
    image: chainpoint/node-web-service
    container_name: web
    build:
      context: ./node-web-service
    depends_on:
      - l5d
      - rabbitmq

  # RabbitMQ Admin Page : http://127.0.0.1:15672/
  rabbitmq:
    restart: always
    image: "rabbitmq:management-alpine"
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    environment:
    - RABBITMQ_DEFAULT_USER=chainpoint
    - RABBITMQ_DEFAULT_PASS=chainpoint

  redis:
    restart: always
    image: "redis:alpine"
    container_name: redis

  # linkerd
  # l5d Admin Page : http://127.0.0.1:9990/
  l5d:
    restart: always
    image: buoyantio/linkerd:0.9.1
    container_name: l5d
    ports:
    - "4140:4140"
    - "9990:9990"
    # we must mount the config file and the disco directory
    volumes:
    - ./linkerd.yaml:/io.buoyant/linkerd.yaml:ro
    - ./disco:/io.buoyant/disco
    command: >
      /io.buoyant/linkerd.yaml
